(()=>{'use strict';
const $=id=>document.getElementById(id);const LABS=[['parameter','Parameter','sandbox'],['contrast','Contrast','contrast'],['timing','Timing','timing'],['motion','Motion','motion'],['kspace','K-Space','kspace'],['spatial','Spatial','spatial'],['artifact','Artifact','artifact']];
const ICONS={parameter:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h9M16 7h4M4 17h4M11 17h9M13 4v6M8 14v6" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>',contrast:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 17c4-11 7-11 9 0 2-8 5-9 9-2" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><path d="M3 6h18" stroke="currentColor" opacity=".35"/></svg>',timing:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 14h3l2-7 3 12 3-10 2 5h5" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M3 21h18" stroke="currentColor" opacity=".35"/></svg>',motion:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 8c4-5 5 8 9 3s5 7 9 3M3 15c4-5 5 8 9 3s5 7 9 3" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>',kspace:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 3v18M9 3v18M15 3v18M19 3v18M3 5h18M3 9h18M3 15h18M3 19h18" stroke="currentColor" opacity=".35"/><circle cx="12" cy="12" r="3.2" fill="currentColor"/></svg>',spatial:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v14H4zM8 5v14M16 5v14M4 10h16M4 15h16" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M2.5 8V3h5M21.5 16v5h-5" fill="none" stroke="currentColor" stroke-width="1.8"/></svg>',artifact:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5h10v10H5zM9 9h10v10H9z" fill="none" stroke="currentColor" stroke-width="1.7"/><path d="M4 20h16" stroke="currentColor" opacity=".35"/></svg>'};
function cv(id,h=122){const c=$(id);if(!c)return null;const d=Math.min(2.5,devicePixelRatio||1),rect=c.getBoundingClientRect(),w=Math.max(180,Math.round(rect.width||300)),rh=Math.max(96,Math.round(rect.height||h||122));c.width=Math.round(w*d);c.height=Math.round(rh*d);const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.fillStyle='#050b13';x.fillRect(0,0,w,rh);x.strokeStyle='rgba(140,190,220,.055)';for(let q=0;q<w;q+=24){x.beginPath();x.moveTo(q,0);x.lineTo(q,rh);x.stroke()}for(let q=0;q<rh;q+=24){x.beginPath();x.moveTo(0,q);x.lineTo(w,q);x.stroke()}return{x,w,h:rh}}
function parameter(){const a=cv('homeParameterPreview');if(!a)return;let m={detail:1,snr:1,time:1};try{m=sandboxMetrics(sandboxState())}catch(e){};[['#52b7ff',m.detail],['#68e1b8',m.snr],['#ffd166',m.time]].forEach(([c,v],i)=>{const y=20+i*30;a.x.fillStyle='rgba(255,255,255,.07)';a.x.fillRect(18,y,a.w-36,8);a.x.fillStyle=c;a.x.fillRect(18,y,(a.w-36)*Math.max(.04,Math.min(1.25,v))/1.25,8)});a.x.fillStyle='#9fb4c1';a.x.font='11px system-ui';a.x.fillText('detail',18,15);a.x.fillText('signal',18,45);a.x.fillText('time',18,75)}
function contrast(){const a=cv('homeContrastPreview');if(!a)return;let s={tr:800,te:20,ti:600,mode:'se'};try{s=contrastState()}catch(e){};[['#9a83ff',.9],['#5be7ff',1.35],['#68e1b8',1.9]].forEach(([c,k])=>{a.x.strokeStyle=c;a.x.lineWidth=2;a.x.beginPath();for(let i=0;i<=100;i++){const t=i/100,xx=14+t*(a.w-28),yy=a.h-14-(1-Math.exp(-t*4/k))*(a.h-30);i?a.x.lineTo(xx,yy):a.x.moveTo(xx,yy)}a.x.stroke()});const marker=14+Math.min(1,s.te/160)*(a.w-28);a.x.strokeStyle='#ffd166';a.x.beginPath();a.x.moveTo(marker,8);a.x.lineTo(marker,a.h-8);a.x.stroke()}
function timing(){const a=cv('homeTimingPreview');if(!a)return;let s={etl:8,center:4};try{s=timingState()}catch(e){};const n=Math.max(2,Math.min(16,+s.etl||8)),center=Math.max(1,Math.min(n,+s.center||Math.ceil(n/2)));a.x.strokeStyle='#5be7ff';a.x.lineWidth=2;a.x.beginPath();a.x.moveTo(10,a.h*.65);for(let i=0;i<n;i++){const xx=24+i*(a.w-48)/Math.max(1,n-1),peak=a.h*.28-(i===center-1?8:0);a.x.lineTo(xx-6,a.h*.65);a.x.lineTo(xx,peak);a.x.lineTo(xx+6,a.h*.65)}a.x.lineTo(a.w-10,a.h*.65);a.x.stroke();const cx=24+(center-1)*(a.w-48)/Math.max(1,n-1);a.x.fillStyle='#ffd166';a.x.beginPath();a.x.arc(cx,a.h*.28-8,4,0,Math.PI*2);a.x.fill()}
function motion(){const a=cv('homeMotionPreview');if(!a)return;let s={amplitude:3,onset:45,cycles:2};try{s=motionState()}catch(e){};const onset=Math.max(0,Math.min(1,(+s.onset||0)/100)),amp=Math.min(28,4*(+s.amplitude||0));a.x.strokeStyle='#ff8f7d';a.x.lineWidth=2;a.x.beginPath();for(let i=0;i<=100;i++){const t=i/100,xx=12+t*(a.w-24),yy=a.h/2+(t<onset?0:Math.sin((t-onset)*Math.PI*2*(+s.cycles||2))*amp);i?a.x.lineTo(xx,yy):a.x.moveTo(xx,yy)}a.x.stroke();const cx=12+onset*(a.w-24);a.x.strokeStyle='rgba(91,231,255,.8)';a.x.beginPath();a.x.moveTo(cx,10);a.x.lineTo(cx,a.h-10);a.x.stroke()}
function kspace(){const a=cv('homeKspacePreview');if(!a)return;let s={mode:'full',amount:100};try{s=kspaceState()}catch(e){};const cx=a.w/2,cy=a.h/2,amt=Math.max(.1,Math.min(1,(+s.amount||100)/100));for(let y=8;y<a.h-8;y+=8)for(let x=10;x<a.w-10;x+=8){const d=Math.hypot((x-cx)/(a.w*.35),(y-cy)/(a.h*.7));let on=true;if(s.mode==='center')on=d<amt;if(s.mode==='outer')on=d>1-amt;if(s.mode==='truncate')on=Math.abs(y-cy)<a.h*.45*amt;if(s.mode==='undersample')on=Math.round((y-8)/8)%Math.max(2,Math.round(1/amt))===0;const q=Math.max(0,1-d);a.x.fillStyle=on?`rgba(255,209,102,${.05+.85*q*q})`:'rgba(255,255,255,.025)';a.x.fillRect(x,y,3,3)}}
function spatial(){const a=cv('homeSpatialPreview');if(!a)return;let s={readFov:100,phaseFov:100,readSamples:256,phaseSamples:256};try{s=spatialState()}catch(e){};const rw=Math.max(.3,Math.min(1,+s.readFov/100)),ph=Math.max(.3,Math.min(1,+s.phaseFov/100)),fw=a.w*.64*rw,fh=a.h*.66*ph,x=(a.w-fw)/2,y=(a.h-fh)/2;a.x.fillStyle='rgba(104,225,184,.07)';a.x.fillRect(x,y,fw,fh);a.x.strokeStyle='#68e1b8';a.x.setLineDash([6,5]);a.x.strokeRect(x,y,fw,fh);a.x.setLineDash([]);const nx=Math.max(4,Math.min(10,Math.round((+s.readSamples||256)/48))),ny=Math.max(3,Math.min(8,Math.round((+s.phaseSamples||256)/56)));a.x.strokeStyle='rgba(82,183,255,.30)';for(let i=1;i<nx;i++){const xx=x+i*fw/nx;a.x.beginPath();a.x.moveTo(xx,y);a.x.lineTo(xx,y+fh);a.x.stroke()}for(let i=1;i<ny;i++){const yy=y+i*fh/ny;a.x.beginPath();a.x.moveTo(x,yy);a.x.lineTo(x+fw,yy);a.x.stroke()}}
function artifact(){const a=cv('homeArtifactPreview');if(!a)return;let s={mode:'motion',strength:55,direction:'x'};try{s=artifactLabState()}catch(e){};const p=Math.max(.15,Math.min(1,(+s.strength||50)/100)),dx=s.direction==='x'?18*p:0,dy=s.direction==='y'?15*p:0;function box(ox,oy,alpha){a.x.strokeStyle=`rgba(214,155,255,${alpha})`;a.x.lineWidth=2;a.x.strokeRect(a.w*.30+ox,a.h*.20+oy,a.w*.32,a.h*.58)}box(0,0,.95);if(s.mode==='motion'||s.mode==='flow'){box(dx,dy,.42);box(dx*2,dy*2,.20)}else if(s.mode==='zipper'){a.x.strokeStyle='rgba(255,143,125,.8)';a.x.lineWidth=3;a.x.beginPath();a.x.moveTo(8,a.h*.66);a.x.lineTo(a.w-8,a.h*.66);a.x.stroke()}else if(s.mode==='wrap'){box(-a.w*.22*p,0,.34);box(a.w*.22*p,0,.25)}else{a.x.strokeStyle='rgba(255,209,102,.55)';a.x.beginPath();a.x.arc(a.w*.55,a.h*.52,12+20*p,0,Math.PI*2);a.x.stroke()}}
const PREV={parameter,contrast,timing,motion,kspace,spatial,artifact};function drawHome(){Object.values(PREV).forEach(f=>{try{f()}catch(e){}})}let raf=0;function queue(){cancelAnimationFrame(raf);raf=requestAnimationFrame(drawHome)}
function switchers(){document.querySelectorAll('[data-v27-shared-switcher]').forEach(h=>{h.classList.add('v27-lab-switcher');h.innerHTML='<button type="button" class="v27-lab-exit" onclick="showHome()" aria-label="Exit Lab and return to Labs home"><span aria-hidden="true">⌂</span><span class="v27-lab-label">Home</span></button>'+LABS.map(([id,label])=>`<button type="button" data-v27-lab="${id}" onclick="openLab('${id}')" aria-label="Open ${label} Lab">${ICONS[id]}<span class="v27-lab-label">${label}</span></button>`).join('')})}function activeLab(id){document.querySelectorAll('[data-v27-lab]').forEach(b=>{const on=b.dataset.v27Lab===id;b.classList.toggle('active',on);on?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')})}
function makeHub(id,title,kicker,items){let b=$(id);if(b)return b;b=document.createElement('div');b.id=id;b.className='v27-hubback';b.setAttribute('aria-hidden','true');b.innerHTML=`<section class="v27-hub" role="dialog" aria-modal="true" aria-labelledby="${id}Title"><div class="v27-hub-head"><div><div class="v27-kicker">${kicker}</div><h2 id="${id}Title">${title}</h2></div><button class="v27-hub-close" aria-label="Close">✕</button></div><div class="v27-hub-grid">${items.map(x=>`<button type="button" data-action="${x[0]}"><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div></section>`;document.body.appendChild(b);b.addEventListener('click',e=>{if(e.target===b||e.target.closest('.v27-hub-close'))close(b);const x=e.target.closest('[data-action]');if(x){close(b);run(x.dataset.action)}});return b}function close(b){b.classList.remove('open');b.setAttribute('aria-hidden','true')}function open(b){b.classList.add('open');b.setAttribute('aria-hidden','false');setTimeout(()=>b.querySelector('button')?.focus(),0)}function run(a){if(a==='parameterref'){go?.('sandbox',true);setTimeout(()=>$('parameterReference')?.scrollIntoView({behavior:'smooth'}),100)}else if(a==='settings')openPreferences?.();else if(a==='search')openPalette?.();else if(a==='premium')openPremiumWorkspace?.();else if(a==='home')showHome?.();else if(a==='compare')openParameterWorkspace?.('compare');else go?.(a)}
window.openV27ReferenceHub=()=>open(makeHub('v27ReferenceHub','MRI Reference','Reference hub',[['parameterref','Parameter Reference','Geometry, signal, efficiency, contrast, artifacts'],['math','Scan Math','Voxel size and acquisition-time relationships'],['rescue','Sequence Rescue','Work backward from the limiting problem'],['artifact','Artifact troubleshooting','Pattern, mechanism, direction, discriminator'],['safety','MR Safety','Evidence chain and escalation routes'],['burn','Thermal / RF','Heating, loops, cables, and setup concepts']]));window.openV27MoreMenu=()=>open(makeHub('v27MoreHub','More MRCC tools','Workspace',[['premium','Premium previews','Advanced interactive concept models'],['compare','Parameter A/B Compare','Compare saved A against the live stack'],['safety','MR Safety','Safety reference and escalation'],['settings','Settings','Text size, contrast, motion, backup'],['search','Search','Find a Lab, sequence, artifact, or reference'],['home','Home','Return to MRCC Home']]));
function intel(section,lab){
  const s=$(section);if(!s||s.querySelector('.v27-intelligence'))return;
  const h=document.createElement('div');
  h.className='v27-intelligence';h.dataset.v27Intel=lab;
  h.innerHTML='<div class="v27-intel-cell"><small>What changed</small><b data-v27-what>Current state</b><span data-v27-wd>Move a control to compare the experiment.</span></div><div class="v27-intel-cell"><small>Why</small><b data-v27-why>Physics relationship</b><span data-v27-yd>The dominant relationship appears here.</span></div><div class="v27-intel-cell"><small>Try next</small><b data-v27-next>Isolate one lever</b><span data-v27-nd>Change one variable and watch the direction.</span></div>';
  const anchorMap={parameter:'#paramModelCard',contrast:'.contrast-layout',timing:'.timing-layout',motion:'.motion-layout',kspace:'.kspace-readouts',spatial:'.spatial-readouts',artifact:'.artifact-lab-grid'};
  let anchor=s.querySelector(anchorMap[lab]||'');
  if(lab==='parameter'&&anchor)anchor=anchor.closest('.grid2')||anchor;
  if(!anchor)anchor=s.querySelector('.section-head,.lab-canvas-head,.contrast-lab-head,.lab-switcher')||s.firstElementChild;
  anchor?.insertAdjacentElement('afterend',h);
}
function setI(l,a,b,c,d,e,f){const h=document.querySelector(`[data-v27-intel="${l}"]`);if(!h)return;[['[data-v27-what]',a],['[data-v27-wd]',b],['[data-v27-why]',c],['[data-v27-yd]',d],['[data-v27-next]',e],['[data-v27-nd]',f]].forEach(([q,v])=>{const x=h.querySelector(q);if(x)x.textContent=v})}
function renderI(){try{const s=sandboxState(),m=sandboxMetrics(s),n=sandboxChangedCount?.(s)||0;setI('parameter',`${n} control${n===1?'':'s'} from baseline`,`Detail ${Math.round(m.detail*100)}% · SNR ${Math.round(m.snr*100)}% · time ${Math.round(m.time*100)}%`,'Tradeoff stack','Resolution, voxel volume, bandwidth, averaging, acceleration, ETL and sampling burden interact.','Change one lever','Use the isolated-control inspector to separate that lever from the full stack.')}catch(e){}try{const s=contrastState(),c=contrastTeachingCue(s);setI('contrast',`${s.mode==='ir'?'IR-like':'SE-like'} timing`,`TR ${Math.round(s.tr)} · TE ${Math.round(s.te)}${s.mode==='ir'?' · TI '+Math.round(s.ti):''}`,c.label||'Contrast emphasis',c.detail||'Timing changes weighting.','Perturb one timing axis',s.mode==='ir'?'Move TI slightly and watch separation.':'Move TE, restore it, then test TR.')}catch(e){}try{const s=timingState(),m=timingMetrics(s);setI('timing',`ETL ${s.etl} · center ${s.center}`,`${m.trains} train${m.trains===1?'':'s'} · center timing ${Math.round(m.effectiveTe)} ms`,'Center timing matters','The echo carrying central k-space strongly influences the effective-TE-like teaching signal.','Move the center echo','Keep ETL fixed and shift the center echo.')}catch(e){}try{const s=motionState();setI('motion',`${s.pattern||'Motion'} · ${Number(s.amplitude||0).toFixed(1)} px`,`Onset ${Math.round(s.onset||0)}% · ${s.order==='centric'?'centric':'linear'} phase order`,'Acquisition timing','The consequence depends on which phase lines are acquired during motion.','Compare ordering','Hold motion fixed and switch linear ↔ centric.')}catch(e){}try{const s=kspaceState(),m=kspaceModeSummary(s);setI('kspace',m.title||'Current mask',m.meta||'Synthetic sampling mask','Mask → image response','Center/peripheral frequencies contribute differently; the mask also creates its own impulse response.','Change mask family','Compare center-only, truncation, and undersampling.')}catch(e){}try{const s=spatialState(),m=spatialMetrics(s),c=spatialTeachingCopy(s,m);setI('spatial',c.short||'Encoding state',`Read FOV ${Math.round(s.readFov)}% · phase FOV ${Math.round(s.phaseFov)}%`,'Coverage ≠ sampling density','FOV controls encoded coverage; sample count controls the pixel grid.','Repair one axis','Change FOV first, then samples.')}catch(e){}try{const s=artifactLabState(),p=artifactProfile(s.mode);setI('artifact',p.pattern||'Artifact',p.footprint||'Pattern fingerprint','Pattern evidence',p.discriminator||p.direction||'Use morphology and encoding behavior.','Flip or compare direction',p.directionHint||'Check phase, frequency, wrap axis, or neither.')}catch(e){}}
function dna(){try{sequenceDnaRank().slice(0,3).forEach(r=>{const c=document.querySelector(`[data-seq-dna-family="${r.id}"]`);if(!c||c.querySelector('.v27-dna-evidence'))return;const b=document.createElement('div');b.className='v27-dna-evidence';const f=x=>x.map(([d,v])=>`<span>${sequenceDnaDimensions[d].label}: ${sequenceDnaLabel(d,v)}</span>`).join('')||'<span>None</span>';b.innerHTML=`<div><small>Matches</small>${f(r.matched)}</div><div class="conflict"><small>Conflicts</small>${f(r.missed)}</div>`;c.appendChild(b)})}catch(e){}}
function canvases(){const m={motionHistoryCanvas:'Synthetic motion displacement across phase-line acquisition.',motionReferenceCanvas:'Stationary synthetic reference phantom.',motionResultCanvas:'Synthetic motion-corrupted reconstruction.',motionLinearCanvas:'Synthetic reconstruction using linear phase ordering.',motionCentricCanvas:'Synthetic reconstruction using centric phase ordering.',ksKspaceCanvas:'Synthetic k-space magnitude map for the active mask.',ksImageCanvas:'Synthetic reconstruction from the active k-space mask.',ksPsfCanvas:'Mathematical impulse response of the active synthetic mask.',spWorldCanvas:'Synthetic object with encoded field-of-view frame.',spReconCanvas:'Synthetic reconstruction illustrating wrap and sampling density.',artifactCanvas:'Stylized MRI artifact teaching pattern; Pattern DNA provides text evidence.'};Object.entries(m).forEach(([id,label])=>{const c=$(id);if(c){c.setAttribute('role','img');c.setAttribute('aria-label',label)}})}
function boot(){switchers();LABS.forEach(([id,,s])=>intel(s,id));canvases();renderI();drawHome();document.querySelectorAll('.lab-home-card').forEach(c=>{const t=c.querySelector('h3')?.textContent?.trim(),b=c.querySelector('.lab-home-open'),id=LABS.find(x=>c.classList.contains('lab-home-'+x[0]))?.[0];if(t&&b)b.setAttribute('aria-label','Open '+t);if(id){const i=c.querySelector('.lab-home-icon');if(i)i.innerHTML=ICONS[id]}});document.addEventListener('input',()=>{requestAnimationFrame(renderI);queue()},{passive:true});document.addEventListener('change',()=>{requestAnimationFrame(renderI);queue()},{passive:true});addEventListener('resize',queue,{passive:true});if(typeof renderSequenceDna==='function'){const old=renderSequenceDna;window.renderSequenceDna=function(){const r=old.apply(this,arguments);requestAnimationFrame(dna);return r};requestAnimationFrame(dna)}if(typeof setWorkspaceTabActive==='function'){window.setWorkspaceTabActive=function(tab='home'){const d={safety:'reference',compare:'labs',more:'reference'}[tab]||tab,m={premium:'more',safety:'more',compare:'more'}[tab]||tab;document.querySelectorAll('#workspaceRail [data-workspace-tab]').forEach(b=>{const on=b.dataset.workspaceTab===d;b.classList.toggle('active',on);on?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')});document.querySelectorAll('#mobileNav [data-workspace-tab]').forEach(b=>{const on=b.dataset.workspaceTab===m;b.classList.toggle('active',on);on?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')})}}if(typeof openLab==='function'){const old=openLab;window.openLab=function(id){activeLab(id);const r=old.apply(this,arguments);requestAnimationFrame(()=>{renderI();drawHome()});return r}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();

;(()=>{'use strict';
const $=id=>document.getElementById(id);
const LAB_SECTION={parameter:'sandbox',contrast:'contrast',timing:'timing',motion:'motion',kspace:'kspace',spatial:'spatial',artifact:'artifact'};
const CONTROL_MAP={
 sbFov:['parameter','FOV'],sbFreq:['parameter','frequency matrix'],sbPhase:['parameter','phase matrix'],sbPhaseFov:['parameter','phase FOV'],sbSlice:['parameter','slice thickness'],sbNex:['parameter','NEX'],sbBw:['parameter','bandwidth'],sbEtl:['parameter','ETL'],sbAccel:['parameter','acceleration'],sbPf:['parameter','partial Fourier'],
 clMode:['contrast','sequence model'],clTr:['contrast','TR'],clTe:['contrast','TE'],clTi:['contrast','TI'],
 timingTr:['timing','TR'],timingFirstEcho:['timing','first echo'],timingSpacing:['timing','echo spacing'],timingEtl:['timing','ETL'],timingCenter:['timing','center echo'],timingPhase:['timing','phase encodes'],timingNex:['timing','NEX'],
 motionMode:['motion','motion pattern'],motionDirection:['motion','translation direction'],motionOrder:['motion','phase-line ordering'],motionAmplitude:['motion','motion amplitude'],motionOnset:['motion','motion onset'],motionCycles:['motion','motion cycles'],
 ksMode:['kspace','mask family'],ksAmount:['kspace','mask amount / acceleration'],
 spPhaseFov:['spatial','phase FOV'],spReadFov:['spatial','read FOV'],spPhaseSamples:['spatial','phase samples'],spReadSamples:['spatial','read samples'],
 artifactSelect:['artifact','artifact evidence pattern'],artifactStrength:['artifact','artifact strength'],artifactDirection:['artifact','display / encoding direction']
};
const lastChange={};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const pct=v=>(Math.round(v*1000)/10)+'%';
const delta=v=>{const n=Math.round((v-1)*100);return (n>0?'+':'')+n+'%'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

function host(lab,title,kicker='Lab Intelligence'){
  const intel=document.querySelector('[data-v27-intel="'+lab+'"]'); if(!intel)return null;
  let box=intel.parentElement.querySelector(':scope > .v271-analysis[data-lab="'+lab+'"]');
  if(!box){box=document.createElement('section');box.className='v271-analysis';box.dataset.lab=lab;box.innerHTML='<div class="v271-analysis-head"><div><small>'+esc(kicker)+'</small><h3>'+esc(title)+'</h3></div><span class="v271-live"><i></i>live model</span></div><div class="v271-analysis-body"></div>';intel.insertAdjacentElement('afterend',box)}
  return box.querySelector('.v271-analysis-body');
}
function bars(rows){
  return '<div class="v271-bars">'+rows.map(r=>'<div class="v271-bar"><div><b>'+esc(r[0])+'</b><span>'+esc(r[2]||'')+'</span></div><div class="v271-track"><i style="--p:'+clamp(r[1])*100+'%;--c:'+(r[3]||'var(--lab-accent,#5be7ff)')+'"></i></div></div>').join('')+'</div>';
}
function parameterAnalysis(){
  const body=host('parameter','What is driving this stack?');if(!body)return;
  try{
    const s=sandboxState(),keys=Object.keys(sbBase),labels={fov:'FOV',mx:'frequency matrix',phase:'phase matrix',phaseFov:'phase FOV',slice:'slice thickness',nex:'NEX',bw:'bandwidth',etl:'ETL',accel:'acceleration',pf:'partial Fourier'};
    const rows=keys.filter(k=>Math.abs(Number(s[k])-Number(sbBase[k]))>1e-9).map(k=>{
      const iso={...sbBase,[k]:s[k]},m=sandboxMetrics(iso);
      const impacts=[['detail',m.detail],['SNR',m.snr],['time',m.time]];
      const score=impacts.reduce((a,[,v])=>a+Math.abs(Math.log(Math.max(.001,v))),0);
      const strongest=impacts.sort((a,b)=>Math.abs(Math.log(b[1]))-Math.abs(Math.log(a[1])))[0];
      return {k,label:labels[k],score,strongest:strongest[0]+' '+delta(strongest[1]),detail:m.detail,snr:m.snr,time:m.time};
    }).sort((a,b)=>b.score-a.score);
    if(!rows.length){body.innerHTML='<div class="v271-empty"><b>Baseline stack</b><span>Move any Parameter control and MRCC will rank its isolated contribution to detail, SNR, and modeled time.</span></div>';return}
    const max=Math.max(...rows.map(r=>r.score),.001),top=rows.slice(0,4);
    body.innerHTML='<div class="v271-driver-grid">'+top.map((r,i)=>'<button type="button" data-v271-inspector="'+r.k+'" class="v271-driver '+(i===0?'lead':'')+'"><span class="v271-rank">'+(i+1)+'</span><div><small>'+esc(r.label)+'</small><b>'+esc(r.strongest)+'</b><span>D '+delta(r.detail)+' · SNR '+delta(r.snr)+' · time '+delta(r.time)+'</span></div><i style="--p:'+Math.max(8,Math.round(r.score/max*100))+'%"></i></button>').join('')+'</div><p class="v271-footnote">Each row isolates one changed lever against the Parameter Lab baseline. It is a teaching decomposition, not a scanner prediction.</p>';
    body.querySelectorAll('[data-v271-inspector]').forEach(b=>b.onclick=()=>{try{setParameterInspector(b.dataset.v271Inspector);document.getElementById('parameterDeepCockpit')?.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){}});
  }catch(e){body.innerHTML='<div class="v271-empty"><b>Driver analysis unavailable</b><span>The underlying Parameter Lab remains active.</span></div>'}
}
function contrastSpread(s){const sig=contrastMaterialsModel.map(m=>contrastSignal(m,s)),mx=Math.max(...sig,.000001),mn=Math.min(...sig);return {spread:(mx-mn)/mx,sig}}
function contrastAnalysis(){
  const body=host('contrast','Which timing lever is separating the signals?');if(!body)return;
  try{
    const s=contrastState(),base=contrastSpread(s).spread,bounds={tr:[300,5000,Math.max(80,s.tr*.08)],te:[10,180,Math.max(5,s.te*.12)],ti:[50,2500,Math.max(30,s.ti*.08)]};
    const levers=(s.mode==='ir'?['tr','te','ti']:['tr','te']).map(k=>{
      const [lo,hi,step]=bounds[k],plus={...s,[k]:clamp(s[k]+step,lo,hi)},minus={...s,[k]:clamp(s[k]-step,lo,hi)},dp=contrastSpread(plus).spread-base,dm=contrastSpread(minus).spread-base;
      const best=Math.abs(dp)>=Math.abs(dm)?{dir:'increase',d:dp}:{dir:'decrease',d:dm};
      return {k,label:k.toUpperCase(),strength:Math.max(Math.abs(dp),Math.abs(dm)),best};
    }).sort((a,b)=>b.strength-a.strength);
    const max=Math.max(...levers.map(x=>x.strength),.001);
    body.innerHTML='<div class="v271-sensitivity">'+levers.map((r,i)=>'<div class="'+(i===0?'lead':'')+'"><small>'+r.label+' local sensitivity</small><b>'+pct(r.strength)+' spread change</b><span>Try '+r.best.dir+' · '+(r.best.d>=0?'separation grows':'separation shrinks')+'</span><i style="--p:'+Math.max(5,r.strength/max*100)+'%"></i></div>').join('')+'</div><div class="v271-callout"><b>Current synthetic spread '+pct(base)+'</b><span>Local sensitivity tests a small timing perturbation around the current state; it does not imply clinical optimization.</span></div>';
  }catch(e){}
}
function timingAnalysis(){
  const body=host('timing','Where is the timing pressure?');if(!body)return;
  try{
    const s=timingState(),m=timingMetrics(s),util=clamp(m.trainSpan/Math.max(1,s.tr)),center=clamp(m.effectiveTe/Math.max(1,m.trainSpan)),trainPressure=clamp(m.trains/40),timePressure=clamp(m.timeSec/180);
    body.innerHTML=bars([['TR occupied',util,Math.round(util*100)+'% of toy TR','#5be7ff'],['Center position',center,'echo '+s.center+' of '+s.etl,'#9a83ff'],['Train count',trainPressure,m.trains+' train'+(m.trains===1?'':'s'),'#68e1b8'],['Toy acquisition burden',timePressure,Math.round(m.timeSec)+' s','#ffd166']])+'<div class="v271-callout '+(!m.fit?'warn':'')+'"><b>'+(m.fit?'Train fits inside toy TR':'Train exceeds toy TR')+'</b><span>Train span '+Math.round(m.trainSpan)+' ms · effective-TE-like center '+Math.round(m.effectiveTe)+' ms · idle '+Math.round(m.idle)+' ms.</span></div>';
  }catch(e){}
}
function motionAnalysis(){
  const body=host('motion','Which phase lines are vulnerable?');if(!body)return;
  try{
    const s=motionState(),a=motionAcquire(s),st=motionLineStats(a),den=Math.max(.001,s.amplitude||1);
    const cells=[];for(let y=0;y<KS_N;y++){const ky=motionSignedIndex(y),rank=a.rankByY[y],d=Math.abs(a.dispByRank[rank]),v=clamp(d/den);cells.push('<i class="'+(Math.abs(ky)<=4?'center':'')+'" style="--v:'+v+'" title="ky '+ky+' · rank '+rank+' · |shift| '+d.toFixed(2)+'"></i>')}
    body.innerHTML='<div class="v271-motion-timeline"><div class="v271-motion-key"><span>outer</span><b>phase-line acquisition vulnerability</b><span>center</span></div><div class="v271-motion-lines">'+cells.join('')+'</div></div><div class="v271-kpis"><div><small>Center-band mean</small><b>'+st.centerMean.toFixed(2)+' px</b></div><div><small>Outer mean</small><b>'+st.outerMean.toFixed(2)+' px</b></div><div><small>Center lines affected</small><b>'+st.centerAffected+' / '+st.centerN+'</b></div><div><small>Center acquired</small><b>rank '+a.centerRank+'</b></div></div>';
  }catch(e){}
}
function kspaceAnalysis(){
  const body=host('kspace','What does this mask retain—and create?');if(!body)return;
  try{
    const s=kspaceState(),masked=kspaceApplyMask(s),e=kspaceEnergyStats(masked),p=kspaceMaskPsf(masked);
    body.innerHTML=bars([['Samples retained',masked.retained,'Rough acquisition burden '+pct(masked.retained),'#52b7ff'],['Fourier energy retained',e.energyRetained,'Energy ≠ diagnostic importance','#ffd166'],['Center-band energy',e.centerRetained,'Broad structure proxy','#68e1b8'],['Outer-band energy',e.outerRetained,'Rapid spatial variation proxy','#9a83ff'],['Off-center mask response',p.sideRatio,'Side response '+pct(p.sideRatio),'#ff8f7d']])+'<div class="v271-callout"><b>Energy efficiency '+e.efficiency.toFixed(2)+'×</b><span>'+esc(kspaceModeSummary(s).meta)+' · mask half-peak support '+p.halfCount+' samples.</span></div>';
  }catch(e){}
}
function spatialAnalysis(){
  const body=host('spatial','Coverage problem or sampling problem?');if(!body)return;
  try{
    const s=spatialState(),m=spatialMetrics(s),copy=spatialTeachingCopy(s,m);
    const readRepair=m.readWrap?'increase read FOV':m.readPixel>1.12?'increase read samples or reduce read FOV':'read axis contained';
    const phaseRepair=m.phaseWrap?'increase phase FOV / anti-alias coverage':m.phasePixel>1.12?'increase phase samples or reduce phase FOV':'phase axis contained';
    body.innerHTML='<div class="v271-axis-grid"><div class="'+(m.readWrap?'warn':'')+'"><small>Read axis</small><b>'+(m.readWrap?'coverage-limited':'coverage contained')+'</b><span>FOV '+Math.round(s.readFov)+'% · pixel '+m.readPixel.toFixed(2)+'× · '+readRepair+'</span></div><div class="'+(m.phaseWrap?'warn':'')+'"><small>Phase axis</small><b>'+(m.phaseWrap?'coverage-limited':'coverage contained')+'</b><span>FOV '+Math.round(s.phaseFov)+'% · pixel '+m.phasePixel.toFixed(2)+'× · '+phaseRepair+'</span></div></div><div class="v271-callout"><b>'+esc(copy.short)+'</b><span>'+esc(copy.detail)+' Fewer samples change the grid; undersized FOV creates periodic wrap in this model.</span></div>';
  }catch(e){}
}
const ART_E={
 motion:{m:'replicas',f:'global',d:'phase',c:'whole'},wrap:{m:'foldover',f:'outside',d:'axis',c:'outside'},chem:{m:'boundary',f:'interface',d:'frequency',c:'orderly'},metal:{m:'distortion',f:'focal',d:'local',c:'irregular'},zipper:{m:'line',f:'global',d:'persistent',c:'system'},trunc:{m:'ringing',f:'edge',d:'sampling',c:'edge'},flow:{m:'replicas',f:'source',d:'phase',c:'pulsatile'},dielectric:{m:'shading',f:'broad',d:'none',c:'smooth'}
};
function artifactMatcher(){
  const body=host('artifact','Match the evidence before choosing the label','Evidence-driven matcher');if(!body)return;
  let box=body.querySelector('.v271-artifact-matcher');
  if(!box){box=document.createElement('div');box.className='v271-artifact-matcher';box.innerHTML='<div class="v271-matcher-controls"><label>Morphology<select data-e="m"><option value="">Any</option><option value="replicas">replicas / ghosts</option><option value="foldover">foldover</option><option value="boundary">bright-dark boundary</option><option value="distortion">focal distortion</option><option value="line">coherent line</option><option value="ringing">edge ringing</option><option value="shading">broad shading</option></select></label><label>Footprint<select data-e="f"><option value="">Any</option><option value="global">distributed / global</option><option value="outside">outside-FOV anatomy</option><option value="interface">fat-water interface</option><option value="focal">focal source</option><option value="edge">sharp edge</option><option value="source">vessel / CSF source</option><option value="broad">broad field</option></select></label><label>Direction behavior<select data-e="d"><option value="">Any</option><option value="phase">phase-related</option><option value="frequency">frequency-related</option><option value="axis">undersized encoded axis</option><option value="local">local B0 / non-axis</option><option value="persistent">persists across anatomy</option><option value="sampling">sampling-boundary</option><option value="none">not directional</option></select></label><label>Strongest clue<select data-e="c"><option value="">Any</option><option value="whole">whole-anatomy replicas</option><option value="outside">plausible outside-FOV anatomy</option><option value="orderly">orderly fat-water edge</option><option value="irregular">irregular local distortion</option><option value="system">system-like stripe</option><option value="edge">alternating bands at edge</option><option value="pulsatile">pulsatile source</option><option value="smooth">smooth shading</option></select></label></div><div class="v271-matcher-results"></div>';body.appendChild(box);box.querySelectorAll('select').forEach(s=>s.addEventListener('change',renderArtifactMatcher))}
  renderArtifactMatcher();
}
function renderArtifactMatcher(){
  const box=document.querySelector('.v271-artifact-matcher');if(!box)return;
  const evidence={};box.querySelectorAll('select').forEach(s=>evidence[s.dataset.e]=s.value);
  const active=Object.values(evidence).filter(Boolean).length,rows=Object.entries(ART_E).map(([id,p])=>{let hit=0,conf=0;for(const k of Object.keys(evidence)){if(!evidence[k])continue;p[k]===evidence[k]?hit++:conf++}return{id,hit,conf,score:active?hit/active:0}}).sort((a,b)=>b.score-a.score||a.conf-b.conf);
  const out=box.querySelector('.v271-matcher-results');if(!active){out.innerHTML='<div class="v271-empty"><b>Add one evidence clue</b><span>MRCC will rank artifact patterns without requiring you to choose the answer first.</span></div>';return}
  out.innerHTML=rows.slice(0,3).map((r,i)=>{const p=artifactProfile(r.id),a=artifacts[r.id];return '<button type="button" data-art-load="'+r.id+'" class="'+(i===0?'lead':'')+'"><small>'+(i===0?'Strongest evidence fit':'Alternate')+'</small><b>'+esc(a?.title||r.id)+' · '+Math.round(r.score*100)+'%</b><span>'+esc(p.discriminator)+'</span></button>'}).join('');
  out.querySelectorAll('[data-art-load]').forEach(b=>b.onclick=()=>{const sel=$('artifactSelect');if(sel){sel.value=b.dataset.artLoad;artifactLabUpdate();sel.scrollIntoView({behavior:'smooth',block:'center'})}});
}
function dnaMatrix(){
  try{
    const root=$('seqDnaAmbiguity');if(!root)return;let box=root.parentElement.querySelector('.v271-dna-matrix');if(!box){box=document.createElement('div');box.className='v271-dna-matrix';root.insertAdjacentElement('afterend',box)}
    const state=sequenceDnaState(),rank=sequenceDnaRank(state).slice(0,3),dims=['prep','echo','readout','output'];
    box.innerHTML='<div class="v271-analysis-head"><div><small>DNA evidence matrix</small><h3>Why the top families rank where they do</h3></div></div><div class="v271-dna-table"><div class="head"><b>Family</b>'+dims.map(d=>'<span>'+esc(sequenceDnaDimensions[d].label)+'</span>').join('')+'</div>'+rank.map(r=>'<div><b>'+esc(r.family.code)+'</b>'+dims.map(d=>{const v=state[d],any=v==='any',match=any||sequenceDnaProfiles[r.id][d]?.includes(v);return '<span class="'+(any?'neutral':match?'match':'miss')+'">'+(any?'—':match?'✓ ':'× ')+esc(any?'not set':sequenceDnaLabel(d,v))+'</span>'}).join('')+'</div>').join('')+'</div><p class="v271-footnote">'+esc(sequenceDnaDifferentiator(rank[0],rank[1]))+'</p>';
  }catch(e){}
}
function desc(id,text){const c=$(id);if(!c)return;let p=$(id+'V271Desc');if(!p){p=document.createElement('p');p.id=id+'V271Desc';p.className='sr-only';c.insertAdjacentElement('afterend',p);c.setAttribute('aria-describedby',p.id)}p.textContent=text}
function canvasDescriptions(){
  try{const s=motionState(),a=motionAcquire(s),st=motionLineStats(a);desc('motionHistoryCanvas','Motion '+s.mode+', '+s.amplitude+' pixel teaching amplitude, begins '+s.onset+' percent through acquisition. Center-band mean displacement '+st.centerMean.toFixed(2)+' pixels.')}catch(e){}
  try{const s=kspaceState(),m=kspaceApplyMask(s),e=kspaceEnergyStats(m);desc('ksKspaceCanvas',kspaceModeSummary(s).title+'. '+pct(m.retained)+' samples and '+pct(e.energyRetained)+' Fourier energy retained.')}catch(e){}
  try{const s=spatialState(),m=spatialMetrics(s),c=spatialTeachingCopy(s,m);desc('spReconCanvas',c.title+'. Read relative pixel width '+m.readPixel.toFixed(2)+' times baseline; phase relative pixel width '+m.phasePixel.toFixed(2)+' times baseline.')}catch(e){}
  try{const s=artifactLabState(),p=artifactProfile(s.mode);desc('artifactCanvas',p.pattern+'. '+p.footprint+'. '+p.directionLogic+'.')}catch(e){}
}
let raf=0;function renderDeep(){cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{parameterAnalysis();contrastAnalysis();timingAnalysis();motionAnalysis();kspaceAnalysis();spatialAnalysis();artifactMatcher();dnaMatrix();canvasDescriptions();for(const [lab,label] of Object.entries(lastChange)){const h=document.querySelector('[data-v27-intel="'+lab+'"]');if(h){const b=h.querySelector('[data-v27-what]'),s=h.querySelector('[data-v27-wd]');if(b)b.textContent=label+' changed';if(s)s.textContent='The analysis below recomputed from the current Lab state.'}}})}
function relocateDiagnostics(){const adv=document.querySelector('.v27-advanced-settings-grid'),sys=$('offlineBar');if(adv&&sys&&!adv.contains(sys)){const wrap=document.createElement('div');wrap.className='v271-diagnostics';wrap.innerHTML='<h4>System & offline diagnostics</h4><p>Cache, network, runtime self-checks, and offline status.</p>';wrap.appendChild(sys);adv.appendChild(wrap)}}
document.addEventListener('input',e=>{const m=CONTROL_MAP[e.target?.id];if(m){lastChange[m[0]]=m[1];renderDeep()}},{passive:true});
document.addEventListener('change',e=>{const m=CONTROL_MAP[e.target?.id];if(m){lastChange[m[0]]=m[1];renderDeep()}},{passive:true});
const oldRender=window.renderSequenceDna;if(typeof oldRender==='function')window.renderSequenceDna=function(){const r=oldRender.apply(this,arguments);requestAnimationFrame(dnaMatrix);return r};
function boot(){document.documentElement.dataset.mrccRelease='28.1';relocateDiagnostics();renderDeep();setTimeout(renderDeep,120);setTimeout(renderDeep,500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
;(()=>{'use strict';
function sfRange(el){if(!el||el.type!=='range')return;const a=Number(el.min||0),b=Number(el.max||100),v=Number(el.value||0),p=b>a?((v-a)/(b-a))*100:0;el.style.setProperty('--sf-fill',Math.max(0,Math.min(100,p))+'%')}
function sfRefresh(){document.querySelectorAll('input[type="range"]').forEach(sfRange);document.querySelectorAll('.card,.lab-home-card,.seqfam-family-card,.premium-card,.v271-analysis,.pref-card').forEach(el=>{if(el.dataset.sfReactive)return;el.dataset.sfReactive='1';el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.setProperty('--sf-x',((e.clientX-r.left)/r.width*100).toFixed(1)+'%');el.style.setProperty('--sf-y',((e.clientY-r.top)/r.height*100).toFixed(1)+'%')},{passive:true});el.addEventListener('pointerleave',()=>{el.style.setProperty('--sf-x','50%');el.style.setProperty('--sf-y','0%')},{passive:true})})}
document.addEventListener('input',e=>{if(e.target?.type==='range')sfRange(e.target)},{passive:true});
document.addEventListener('change',e=>{if(e.target?.type==='range')sfRange(e.target)},{passive:true});
const sfObs=new MutationObserver(m=>{if(m.some(x=>x.type==='childList'))requestAnimationFrame(sfRefresh)});
function sfBoot(){document.documentElement.dataset.mrccRelease='28.1';sfRefresh();sfObs.observe(document.body,{subtree:true,childList:true});setTimeout(sfRefresh,300)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',sfBoot,{once:true});else sfBoot();
})();
;(()=>{'use strict';
const pulseTargets='.comparecard,.kpi,.result,.state,.v27-intel-cell,.v271-analysis,.contrast-summary,.timing-summary,.motion-summary>div,.kspace-readouts>div,.spatial-axis-card';
function sfPulse(el){if(!el)return;el.classList.remove('sf-updated');void el.offsetWidth;el.classList.add('sf-updated');setTimeout(()=>el.classList.remove('sf-updated'),520)}
function sfWakeFromControl(control){
  const section=control.closest('.section');if(!section)return;
  const near=control.closest('.card')||section;
  const output=control.parentElement?.querySelector('output')||control.closest('.field,.sliderline,.contrast-slider,.timing-slider,.motion-slider,.kspace-slider,.spatial-slider,.artifact-lab-slider')?.querySelector('output');
  sfPulse(output||near);
  const visible=section.querySelectorAll(pulseTargets);for(let i=0;i<Math.min(visible.length,3);i++)sfPulse(visible[i]);
}
document.addEventListener('input',e=>{if(e.target?.matches('input[type="range"],input[type="number"]'))requestAnimationFrame(()=>sfWakeFromControl(e.target))},{passive:true});
document.addEventListener('change',e=>{if(e.target?.matches('select,input[type="checkbox"],input[type="radio"]'))requestAnimationFrame(()=>sfWakeFromControl(e.target))},{passive:true});
})();